### ISSUE TITLE
Bones theme specification - bare bones pass

### ISSUE THREAD

**Issue by j33ff** [lemonstand/lscloud-theme-bones#1]
**A bare bones theme created for LemonStand**
- [ ] HTML/CSS/JavaScript
- [ ] responsive
- [ ] framework to be used?
- [ ] automated
- [ ] extensible
- [ ] better libraries
- [ ] easier to find things
- [ ] reduce partials
- [ ] reduce the amount of files

**Tasks**
- [x] libs inspec -AF
- [x] File Structure -AF
- [ ] ls bones setup -JF
- [ ] shell out -JF
- [ ] Design/wireframes -AF
- [ ] CSS -JF

**Tools Used**
- Bourbon/neat
- jQuery
- HTML5

@af19
