### ISSUE TITLE
Tom's tasks

### ISSUE THREAD

**Issue by tomcornall** [lemonstand/lscloud-theme-bones#2]
@robotpony @af19

**Tasks**
- [x] File Structure
- [x] html/twig for pages/partials
- [x] html5 semantic elements
- [x] User registration/login
- [x] Product reviews
- [x] Help with design, wireframes, css

**Setup Tools**
- [x] gulp
- [x] gulp-sass (https://www.npmjs.com/package/gulp-sass)
- [x] node-bourbon (https://www.npmjs.com/package/node-bourbon)
- [x] node-neat (https://www.npmjs.com/package/node-neat)
- [x] gulp-minify-css (https://www.npmjs.com/package/gulp-minify-css)
- [x] gulp-jshint (https://www.npmjs.com/package/jshint)
- [x] gulp-concat (https://www.npmjs.com/package/concat)
- [x] gulp-uglify (https://www.npmjs.com/package/gulp-uglify)
- [x] gulp-rename (https://www.npmjs.com/package/gulp-rename)
- [x] glup-notify (https://www.npmjs.com/package/gulp-notify)
